### ISSUE TITLE
AttributeError: 'memoryview' object has no attribute 'decode'

### ISSUE THREAD

**Issue by rom1v** [OfflineIMAP/offlineimap3#65]
#### General informations

- system/distribution (with version): Debian sid
- offlineimap version (`offlineimap -V`): `offlineimap v7.3.0, imaplib2 v3.05, Python v3.9.2, OpenSSL 1.1.1k  25 Mar 2021`
- Python version: 3.9.2
- server name or domain: my own domain 
- CLI options: none (`offlineimap`)

#### Configuration file offlineimaprc

```
[general]
accounts = MyAccount

[Account MyAccount]
localrepository = Local
remoterepository = Remote

[Repository Local]
type = Maildir
localfolders = ~/Maildir

[Repository Remote]
type = IMAP
remotehost = (mydomain)
remoteuser = (myuser)
remotepassfile = ...
ssl = yes
cert_fingerprint = ...
maxconnections = 1
```

#### Logs, error

```
Copy message from Remote:INBOX:
 ERROR: Copying message 30940 [acc: MyAccount]
  decoding with 'iso885"; 	name' codec failed (AttributeError: 'memoryview' object has no attribute 'decode')
Thread 'Copy message from Remote:INBOX' terminated with exception:
Traceback (most recent call last):
  File "/usr/share/offlineimap3/offlineimap/imaputil.py", line 406, in utf7m_decode
    for c in binary.decode():
AttributeError: 'memoryview' object has no attribute 'decode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/offlineimap3/offlineimap/threadutil.py", line 146, in run
    Thread.run(self)
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/offlineimap3/offlineimap/folder/Base.py", line 802, in copymessageto
    message = self.getmessage(uid)
  File "/usr/share/offlineimap3/offlineimap/folder/IMAP.py", line 342, in getmessage
    data = self._fetch_from_imap(str(uid), self.retrycount)
  File "/usr/share/offlineimap3/offlineimap/folder/IMAP.py", line 908, in _fetch_from_imap
    ndata1 = self.parser['8bit-RFC'].parsebytes(data[0][1])
  File "/usr/lib/python3.9/email/parser.py", line 123, in parsebytes
    return self.parser.parsestr(text, headersonly)
  File "/usr/lib/python3.9/email/parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/usr/lib/python3.9/email/parser.py", line 56, in parse
    feedparser.feed(data)
  File "/usr/lib/python3.9/email/feedparser.py", line 176, in feed
    self._call_parse()
  File "/usr/lib/python3.9/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/usr/lib/python3.9/email/feedparser.py", line 385, in _parsegen
    for retval in self._parsegen():
  File "/usr/lib/python3.9/email/feedparser.py", line 256, in _parsegen
    if self._cur.get_content_type() == 'message/delivery-status':
  File "/usr/lib/python3.9/email/message.py", line 578, in get_content_type
    value = self.get('content-type', missing)
  File "/usr/lib/python3.9/email/message.py", line 471, in get
    return self.policy.header_fetch_parse(k, v)
  File "/usr/lib/python3.9/email/policy.py", line 163, in header_fetch_parse
    return self.header_factory(name, value)
  File "/usr/lib/python3.9/email/headerregistry.py", line 601, in __call__
    return self[name](name, value)
  File "/usr/lib/python3.9/email/headerregistry.py", line 196, in __new__
    cls.parse(value, kwds)
  File "/usr/lib/python3.9/email/headerregistry.py", line 445, in parse
    kwds['parse_tree'] = parse_tree = cls.value_parser(value)
  File "/usr/lib/python3.9/email/_header_value_parser.py", line 2675, in parse_content_type_header
    ctype.append(parse_mime_parameters(value[1:]))
  File "/usr/lib/python3.9/email/_header_value_parser.py", line 2569, in parse_mime_parameters
    token, value = get_parameter(value)
  File "/usr/lib/python3.9/email/_header_value_parser.py", line 2492, in get_parameter
    token, value = get_value(value)
  File "/usr/lib/python3.9/email/_header_value_parser.py", line 2403, in get_value
    token, value = get_quoted_string(value)
  File "/usr/lib/python3.9/email/_header_value_parser.py", line 1294, in get_quoted_string
    token, value = get_bare_quoted_string(value)
  File "/usr/lib/python3.9/email/_header_value_parser.py", line 1223, in get_bare_quoted_string
    token, value = get_encoded_word(value)
  File "/usr/lib/python3.9/email/_header_value_parser.py", line 1064, in get_encoded_word
    text, charset, lang, defects = _ew.decode('=?' + tok + '?=')
  File "/usr/lib/python3.9/email/_encoded_words.py", line 181, in decode
    string = bstring.decode(charset)
AttributeError: decoding with 'iso885"; 	name' codec failed (AttributeError: 'memoryview' object has no attribute 'decode')
```

On the server, I found a file containing the UID 30940. Its content is UTF-8:
```
$ file cur/1374247664.30940_1.serv:2,S
./cur/1374247664.30940_1.serv:2,S: SMTP mail, UTF-8 Unicode text
```

And this mail contains headers:
```
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset="utf-8"
```

#### Steps to reproduce the error

For me, just rerun `offlineimap`.

**Comment by jishac** [comment]
@rom1v, are you able to provide a sample or sanitized email that causes the issue?

In particular it looks like the issue is from a problematic RFC 2047/2243 encoded word in the header.  From the logs `decoding with 'iso885";` the header probably contains ASCII text starting with `=?iso885?` which is not any encoding I am familiar with.  However the email library should handle cases where the words are not properly encoded.  Also, I am not sure where the memoryview object is being generated...

**Comment by rom1v** [comment]
> are you able to provide a sample or sanitized email that causes the issue?

Yes, in fact it's not sensitive at all.

Here it is in base64 to preserve its integrity:

```console
$ base64 cur/1374247664.30940_1.serv:2,S
UmV0dXJuLVBhdGg6IDxzZWVudGhpc25ldEBnbWFpbC5jb20+ClgtU3BhbS1DaGVja2VyLVZlcnNp
b246IFNwYW1Bc3Nhc3NpbiAzLjMuMiAoMjAxMS0wNi0wNikgb24gc2Vydi5yb20xdi5jb20KWC1T
cGFtLUxldmVsOiAKWC1TcGFtLVN0YXR1czogTm8sIHNjb3JlPTAuNyByZXF1aXJlZD02LjAgdGVz
dHM9RlJFRU1BSUxfRlJPTSxTUEZfTkVVVFJBTCwKCVRfVE9fTk9fQlJLVFNfRlJFRU1BSUwgYXV0
b2xlYXJuPW5vIHZlcnNpb249My4zLjIKWC1PcmlnaW5hbC1Ubzogcm9tK3NlZW50aGlzQHJvbTF2
LmNvbQpEZWxpdmVyZWQtVG86IHJvbStzZWVudGhpc0Byb20xdi5jb20KUmVjZWl2ZWQ6IGZyb20g
c2VlbnRoaXMubmV0IChzZC0xOTIxNi5kZWRpYm94LmZyIFs4OC4xOTAuMTEuNV0pCglieSByb20x
di5jb20gKFBvc3RmaXgpIHdpdGggRVNNVFAgaWQgNDkzQTYzODA0MTUKCWZvciA8cm9tK3NlZW50
aGlzQHJvbTF2LmNvbT47IEZyaSwgMTkgSnVsIDIwMTMgMTc6Mjc6NDQgKzAyMDAgKENFU1QpClJl
Y2VpdmVkOiBieSBzZWVudGhpcy5uZXQgKFBvc3RmaXgsIGZyb20gdXNlcmlkIDMzKQoJaWQgNzlF
MkIzMzZFMEFBOyBGcmksIDE5IEp1bCAyMDEzIDE3OjI0OjA2ICswMjAwIChDRVNUKQpUbzogcm9t
K3NlZW50aGlzQHJvbTF2LmNvbQpTdWJqZWN0OiBTZWVudGhpcyAtIEZpbCB2b3VzIHN1aXQgc3Vy
IFNlZW50aGlzLgpYLVBIUC1PcmlnaW5hdGluZy1TY3JpcHQ6IDMzOmNsYXNzLnBocG1haWxlci5w
aHAKRGF0ZTogRnJpLCAxOSBKdWwgMjAxMyAxNzoyNDowNiArMDIwMApGcm9tOiAiU2VlbnRoaXMg
PG5vLXJlcGx5QHNlZW50aGlzLm5ldD4iIDxTZWVudGhpcyA8bm8tcmVwbHlAc2VlbnRoaXMubmV0
Pj4KTWVzc2FnZS1JRDogPDczOGU1NzdjYjE1ZjRmYjVhNTRkNzRjNTBhMzA5MThhQHNlZW50aGlz
Lm5ldD4KWC1Qcmlvcml0eTogMwpYLU1haWxlcjogUEhQTWFpbGVyIDUuMSAocGhwbWFpbGVyLnNv
dXJjZWZvcmdlLm5ldCkKRXJyb3JzLVRvOiBzZWVudGhpc25ldEBnbWFpbC5jb20KTUlNRS1WZXJz
aW9uOiAxLjAKQ29udGVudC1UcmFuc2Zlci1FbmNvZGluZzogOGJpdApDb250ZW50LVR5cGU6IHRl
eHQvcGxhaW47IGNoYXJzZXQ9InV0Zi04IgoKCgpCb25qb3VyIMKub20sCgpGaWwgKEBmaWwpIHZv
dXMgc3VpdCBzdXIgU2VlbnRoaXMuCmh0dHA6Ly9zZWVudGhpcy5uZXQvcGVvcGxlL2ZpbAoKCgot
LS0tLS0tLS0KUG91ciBuZSBwbHVzIHJlY2V2b2lyIGQnYWxlcnRlcyBkZSBTZWVudGhpcywKIHZv
dXMgcG91dmV6IHLDqWdsZXIgdm9zIHByw6lmw6lyZW5jZXMgZGFucyB2b3RyZSBwcm9maWwKaHR0
cDovL3NlZW50aGlzLm5ldAoKCg==
```

**Comment by jishac** [comment]
Hmm, odd.  That message parses OK in my setup.  I wonder if something is going wrong with imaplib return of the data?  The attached email doesn't seem to have any encoded words, so I'm not sure why we have that backtrace.  I am wondering if there is any other debugging that could be added to the source to provide additional information.  Perhaps a catch around the parsing and if it fails, dump the message (`data[0][1]`) or at least search for the message-id and dump that.

**Comment by jishac** [comment]
@rom1v I used your message extract (which looks to match the error produced and has clear folding errors) and constructed a bare bones test email around it.  When running a standalone parser across the test email it seemed to handle the message just fine.  I tried adding the problematic lines to different parts of the message, such as the base header and as part of a multipart header.  Although it is entirely possible that I missed the proper test case.

I have a conceptual test patch to gather more info about what might be going on.  This patch wraps the parser call in a try block and will elaborate on the type of data that was parsed.  It will be interesting to see if a memoryview object is reported.  The patch also dumped the message-id in an attempt to have a positive match of the source message (although it looks like you may have already found it)

```
diff --git a/offlineimap/folder/IMAP.py b/offlineimap/folder/IMAP.py
index 16d65da..6c977ed 100644
--- a/offlineimap/folder/IMAP.py
+++ b/offlineimap/folder/IMAP.py
@@ -905,7 +905,20 @@ class IMAPFolder(BaseFolder):
         # Convert email, d[0][1], into a message object (from bytes) 
 
         ndata0 = data[0][0].decode('utf-8')
-        ndata1 = self.parser['8bit-RFC'].parsebytes(data[0][1])
+        try: ndata1 = self.parser['8bit-RFC'].parsebytes(data[0][1])
+        except:
+          e = exc_info()
+          response_type = type(data[0][1]).__name__
+          try: msg_id = \
+            re.search(b"message-id:.*(<[A-Za-z0-9!#$%&'*+-/=?^_`{}|~.@ ]+>)",
+            re.split(b'[\r]?\n[\r]?\n', bytes(data[0][1]))[0], re.IGNORECASE).group(1)
+          except AttributeError:
+            # No match
+            msg_id = b"<Unknown Msg-ID>"
+          raise OfflineImapError(
+            "Exception parsing message ({} type {}) from imaplib.\n {}: {}".format(
+              msg_id, response_type, e[0].__name__, e[1]),
+            OfflineImapError.ERROR.MESSAGE)
         ndata = [ndata0, ndata1]
 
         return ndata
```

Are you able to test using this patch?

**Comment by rom1v** [comment]
Thank you.

I am trying to use offlineimap3 from sources, but I failed:

```console
$ pip3 install -r requirements.txt 
Collecting gssapi[kerberos]
  Using cached gssapi-1.6.12.tar.gz (1.1 MB)
Collecting portalocker[cygwin]
  Using cached portalocker-2.3.0-py2.py3-none-any.whl (15 kB)
Collecting rfc6555
  Using cached rfc6555-0.0.0-py2.py3-none-any.whl (10 kB)
Collecting distro
  Using cached distro-1.5.0-py2.py3-none-any.whl (18 kB)
ERROR: Could not find a version that satisfies the requirement imaplib2~=3.5
ERROR: No matching distribution found for imaplib2~=3.5
```

```console
$ apt show python3-imaplib2 
Package: python3-imaplib2
Version: 2.57-5.2
```

```console
$ pip3 install imaplib2
Collecting imaplib2
  Downloading imaplib2-2.45.0-py2.py3-none-any.whl (24 kB)
Installing collected packages: imaplib2
Successfully installed imaplib2-2.45.0
```

:thinking: 

Here is the mail: https://tmp.rom1v.com/offlineimap_mail

**Comment by jishac** [comment]
The requirement of imaplib2 originated from [PR #53](https://github.com/OfflineIMAP/offlineimap3/pull/53/files) that I needed to partially revert.  On my local system I've installed offlineimap3 from source the 'old way'.  Uninstalling the distribution package and running `python3 setup.py install --user` in the cloned git repository

**Comment by dovf** [comment]
Hi, @jishac !

I've been experiencing the same problem (also on debian sid). Today I finally got a chance to play around with this, and tried applying your suggested patch -- it's a big improvement! The problem still occurs, but at least now the sync continues, and at the end of the run all of the ERRORs are listed. See the output I get below.

(BTW, I also had a lot of trouble installing with pip from source, I finally used #61 which enabled me to install via pip from a local checkout, though even then if installed the wrong version of imaplib2, I had to manually pip-install the correct version of imaplib2.)

```
ERROR: Exceptions occurred during the run!
ERROR: Exception parsing message (b'<0b013490c39840e4b597f9b2b76e31f5@XXXXXXX>' type bytes) from imaplib.
 AttributeError: decoding with 'iso-8859-8-i' codec failed (AttributeError: 'memoryview' object has no attribute 'decode')

Traceback:
  File "/home/dov/proj/offlineimap3/offlineimap/folder/Base.py", line 802, in copymessageto
    message = self.getmessage(uid)
  File "/home/dov/proj/offlineimap3/offlineimap/folder/Gmail.py", line 69, in getmessage
    data = self._fetch_from_imap(str(uid), self.retrycount)
  File "/home/dov/proj/offlineimap3/offlineimap/folder/IMAP.py", line 918, in _fetch_from_imap
    raise OfflineImapError(
```
(The same error appears over and over for multiple messages, all from the same sender...)

**Comment by jishac** [comment]
Hi @dovf, thanks for running with the patch!  That is a very interesting result.  It seems the email library is handed bytes, but somewhere in the logic chain for the email library a memoryview object is created?  A quick scan of the library source, it seems that the email library does not directly create any memoryview objects.  So I wonder if it is leveraging a library that does return them or if a call is failing because of mangled input?

However, unlike the case earlier in this thread, "iso-8859-8-i" is a valid coding, so I would be curious if you notice anything broken with the emails from that sender (you note multiple errors all from the same source)

I have been unable to reproduce the issue with the email snips thus far.  It would be great to get a test email.  If anyone experiencing this bug would like to test the condition outside offlineimap, here is the simple test script I have been using:
```
import traceback, sys, re

from email import policy
from email.parser import BytesParser

my_policy={}
my_parser={}
my_policy['8bit'] = policy.default.clone(cte_type='8bit',utf8=True,refold_source='none')
#my_policy['8bit-RFC'] = policy.default.clone(cte_type='8bit',utf8=True,refold_source='none', linesep='\r\n')
for policy in my_policy:
  my_parser[policy] = BytesParser(policy=my_policy[policy])


for filename in sys.argv[1:]:
  back_trace = ""
  try:
    fd = open(filename, 'rb')
    fbytes = fd.read()
    message_id = re.search(b"message-id:.*(<[\"]?[A-Za-z0-9!#$%&'*+-/=?^_`{}|~.@ ]+[\"]?>)",
        re.split(b'[\r]?\n[\r]?\n',fbytes)[0],(re.IGNORECASE|re.DOTALL)).group(1)
    fd.close()
    print("Processing file: {}, Message-ID: {}".format(filename,message_id))
  except (OSError) as err:
    print("File access error: {}".format(err))
    continue
  for policy in my_policy:
    print("Testing {} with policy {}".format(filename,policy))
    try: msg = my_parser[policy].parsebytes(fbytes)
    except Exception as err:
      print(" Parser Exception!:",err)
      back_trace += traceback.format_exc()
      continue
    print(" Defects: {}".format(msg.defects))
    try: out_bytes = msg.as_bytes(policy=my_policy[policy])
    except Exception as err:
      print(" Output Exception!:",err)
      out_bytes = b''
      back_trace += traceback.format_exc()
    print(" Binary output of as_bytes() matches original message? ... {}".format((fbytes == out_bytes)))
  print(back_trace)
```

**Comment by thekix** [comment]
Hi!

after apply the patches of issue #72, @rom1v do you continue with the problems?
How can I help?

Best Regards,
kix

**Comment by thekix** [comment]
Bug should be solved. No reply from user. Closing. Re-open if needed.

**Comment by potuz** [comment]
I continue seeing this error on Arch linux
```
$ offlineimap --version
8.0.0
$ uname -a 
Linux sala432 5.16.12-arch1-1 #1 SMP PREEMPT Wed, 02 Mar 2022 12:22:51 +0000 x86_64 GNU/Linux

 *** Finished account 'gmail' in 0:25
ERROR: Exceptions occurred during the run!
ERROR: Exception parsing message with ID (<650772795.95023.1639763900224@emshlp2003.sabre.com>) from imaplib (response type: bytes).
 AttributeError: 'memoryview' object has no attribute 'decode'

Traceback:
  File "/usr/lib/python3.10/site-packages/offlineimap/folder/Base.py", line 810, in copymessageto
    message = self.getmessage(uid)
  File "/usr/lib/python3.10/site-packages/offlineimap/folder/IMAP.py", line 343, in getmessage
    data = self._fetch_from_imap(str(uid), self.retrycount)
  File "/usr/lib/python3.10/site-packages/offlineimap/folder/IMAP.py", line 910, in _fetch_from_imap
    raise OfflineImapError(

```

**Comment by mdengler** [comment]
Possibly related to https://bugs.python.org/issue43818 /  https://github.com/python/cpython/pull/32137 and

**Comment by sudipm-mukherjee** [comment]
@thekix @jishac do you need to reopen this issue based on the comment from @NoSuck ?

@NoSuck I (as the Debian package maintainer) am already aware of your comment (issue). But @thekix and @jishac are the expert.

**Comment by NoSuck** [comment]
Thank you, @sudipm-mukherjee, for keeping this useful software available on Debian!

I tried the backports package `7.3.3+dfsg1-1+0.0~git20211018.e64c254+dfsg-1~bpo11+1`, but the issue remains.  For me, it appears in the `nametrans` functions of local repositories—even with test bodies like the following:

```
def LocalToRemote(s):
	return b"TEST".decode('imap4-utf-7')
```

```
*** Processing account example.net・test
Establishing connection to example.net:993 (example.net・test-remote)
ERROR: While attempting to sync account 'example.net・test'
  decoding with 'imap4-utf-7' codec failed (AttributeError: 'memoryview' object has no attribute 'decode')

Traceback:
  File "/usr/share/offlineimap3/offlineimap/accounts.py", line 298, in syncrunner
    self.__sync()
  File "/usr/share/offlineimap3/offlineimap/accounts.py", line 375, in __sync
    localrepos.getfolders()
  File "/usr/share/offlineimap3/offlineimap/repository/Maildir.py", line 227, in getfolders
    self.folders = self._getfolders_scandir(self.root)
  File "/usr/share/offlineimap3/offlineimap/repository/Maildir.py", line 214, in _getfolders_scandir
    file_desc = self.getfoldertype()(self.root, foldername,
  File "/usr/share/offlineimap3/offlineimap/folder/Maildir.py", line 56, in __init__
    super(MaildirFolder, self).__init__(name, repository)
  File "/usr/share/offlineimap3/offlineimap/folder/Base.py", line 78, in __init__
    self.visiblename = repository.nametrans(name)
  File "/home/test/.config/offlineimap/test.py", line 193, in LocalToRemote
    return b"TEST".decode('imap4-utf-7')
```

**Comment by jishac** [comment]
> Should the patches from #72 be enough to resolve the issue?

The patches in #72 wrap the calls so that if this error should occur, it should not stop offlineimap from proceeding to process other messages.  Unfortunately, I was [unable to replicate this issue](https://github.com/OfflineIMAP/offlineimap3/issues/65#issuecomment-853233465) with a test message.  So the cause of getting a memoryview object we were not expecting was never ascertained, including if the cause is in offlineimap or imaplib

**Comment by rom1v** [comment]
I retested with offlineimap 8.0.0, the error is still present but is now catched and does not prevent the synchronization of other e-mails:

```
$ offlineimap -V
offlineimap v8.0.0, imaplib2 v3.05, Python v3.10.4, OpenSSL 3.0.3 3 May 2022
```

```
ERROR: Exceptions occurred during the run!
ERROR: Exception parsing message with ID (<795337943.480298.1617351786993@cg95-prod-batch.lan.nfrance.net>) from imaplib (response type: bytes).
 AttributeError: 'memoryview' object has no attribute 'decode'

Traceback:
  File "/usr/share/offlineimap3/offlineimap/folder/Base.py", line 810, in copymessageto
    message = self.getmessage(uid)
  File "/usr/share/offlineimap3/offlineimap/folder/IMAP.py", line 343, in getmessage
    data = self._fetch_from_imap(str(uid), self.retrycount)
  File "/usr/share/offlineimap3/offlineimap/folder/IMAP.py", line 910, in _fetch_from_imap
    raise OfflineImapError(
```

(the output is truncated as is in the console)

**Comment by NoSuck** [comment]
For anyone already using [imapfilter](https://github.com/lefcha/imapfilter) for, say, IDLE notifications, you can easily create your own maildir because the format is so simple:

```
local path_msg = 'maildir/new/' .. time .. '_' .. i .. '.' .. pid .. '.' .. host .. ',U=' .. uid
local f = assert(io.open(path_msg, 'w'))
f:write(mbox['INBOX'][uid]:fetch_message())
```

This renders OfflineIMAP obsolete.

**Comment by mb720** [comment]
I just stumbled upon this with OfflineIMAP 8.0.0 on Arch Linux. The error is:

    Copy message UID -1 (1/1) liwest-local:INBOX.Old -> liwest-remote:INBOX.Old
    ERROR: Exception parsing message with ID (<Unknown Message-ID>) from file (cur/1658314684.129872_8121.zurich:2,S).
    AttributeError: 'memoryview' object has no attribute 'decode'

I noticed that the file name `1658314684.129872_8121.zurich:2,S` is shorter than other emails in the same directory which look like this:

    1658315021_0.207480.zurich,U=1,FMD5=9aa46a9b0eb82bce7f4558eec4f049f2:2,S

The content of that file (i.e., the email) is [here](https://gist.github.com/mb720/03934f08d3061792175fcb00240f3b4c).

Thanks for looking into this and thanks a ton for OfflineIMAP!

**Comment by stepanov1975** [comment]
Have same issue
```
Account sync gmail:
 *** Processing account gmail
 Establishing connection to imap.gmail.com:993 (RemoteGmail)
Folder [Gmail]/All Mail [acc: gmail]:
 Syncing [Gmail]/All Mail: Gmail -> Maildir
 Copy message UID 114230 (1/1) RemoteGmail:[Gmail]/All Mail -> LocalGmail:[Gmail].All Mail
Copy message from RemoteGmail:[Gmail]/All Mail:
 ERROR: Exception parsing message with ID (<AM3PR07MB0647EEC127A6A98E599011B0B89A0@AM3PR07MB0647.eurprd07.prod.outlook.com>) from imaplib (response type: bytes).
 AttributeError: 'memoryview' object has no attribute 'decode'
Account sync gmail:
 *** Finished account 'gmail' in 0:18
ERROR: Exceptions occurred during the run!
ERROR: Exception parsing message with ID (<AM3PR07MB0647EEC127A6A98E599011B0B89A0@AM3PR07MB0647.eurprd07.prod.outlook.com>) from imaplib (response type: bytes).
 AttributeError: 'memoryview' object has no attribute 'decode'

Traceback:
  File "/usr/share/offlineimap3/offlineimap/folder/Base.py", line 810, in copymessageto
    message = self.getmessage(uid)
  File "/usr/share/offlineimap3/offlineimap/folder/Gmail.py", line 69, in getmessage
    data = self._fetch_from_imap(str(uid), self.retrycount)
  File "/usr/share/offlineimap3/offlineimap/folder/IMAP.py", line 910, in _fetch_from_imap
    raise OfflineImapError(
```
Ubuntu 22.04.2 LTS

**Comment by mkamensky** [comment]
Just to update that I had the same problem, and #112 it for me
